# Generated by Django 5.2 on 2025-04-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='blog_videos/')),
                ('categorie', models.CharField(choices=[('tech', 'Technologie'), ('dev', 'Développement'), ('life', 'Vie personnelle')], max_length=50)),
                ('auteur', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('demolien', models.URLField(max_length=500)),
                ('repolien', models.URLField(max_length=500)),
                ('technologies', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='projets_images/')),
            ],
        ),
    ]
