# Generated by Django 5.2 on 2025-05-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='technologies',
            field=models.JSONField(default=list, max_length=300),
        ),
    ]
