# Generated by Django 5.2 on 2025-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_projet_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='technologies',
            field=models.JSONField(default=list),
        ),
    ]
