# Generated by Django 5.2 on 2025-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_projet_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categorie',
            field=models.CharField(choices=[('Tech', 'Technologie'), ('Dev', 'Développement'), ('life', 'Vie personnelle'), ('Actu', 'Actualité'), ('Design', 'Design'), ('Formation', 'Formation')], max_length=50),
        ),
    ]
