# Generated by Django 5.2 on 2025-06-05 12:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blog_likes_alter_blog_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categorie',
            field=models.CharField(choices=[('Tech', 'Technologie'), ('Dev', 'Développement'), ('life', 'Vie personnelle'), ('Actu', 'Actualité'), ('Design', 'Design')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
