# Generated by Django 5.2 on 2025-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blog_categorie_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
